name: Pipelines Demo
on: [push]
jobs:
  Trigger-Reimage-Pipeline:
    environment: gh-action-demo
    runs-on: ubuntu-latest
    steps:
      - name: Reimage Pipeline Trigger
        run: |
          curl https://api.sta.cycle.io/v1/pipelines/655555320e08dadd41879a08/trigger \
            -H "Content-Type: application/json" \
            -d '{ "secret": "secret_Qf5W5N0Ad2VluscIcoWaCpuNaBC2af9OHfoELFE3sLXhxqfUo4MGImDAl2mF" }' \
            -X POST
