name: Pipelines Demo
on: [push]
jobs:
  Trigger-Reimage-Pipeline:
    environment: gh-action-demo
    runs-on: ubuntu-latest
    steps:
      - name: Reimage Pipeline Trigger
        run: |
          curl https://api.cycle.io/v1/pipelines/65429f7ed0208f30bb4ee3e8/trigger \
            -H "Content-Type: application/json" \
            -d '{ \"secret\": \"secret_t3GpmrSFmr4b4Yi2tPeMQHES4qChrVTmRVcYBAM0xThUIWjuVzFxVip394um\" }' \
            -X POST
