name: Pipelines Demo
on: [push]
jobs:
  Trigger-Reimage-Pipeline:
    environment: gh-action-demo
    runs-on: ubuntu-latest
    steps:
      - name: Reimage Pipeline Trigger
        run: |
          curl https://api.dev.cycle.io/v1/pipelines/64add2eb41b1050168f8765a/trigger \
            -H "Content-Type: application/json" \
            -d "{ \"secret\": \"secret_DOqkaILjMU6EzlYN9hXIxijUz1hewrU8K1f28Vxly5DHW0psemlKE7n0qhGS\" }" \
            -X POST
